/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyButton {
        "disabled": boolean;
        "type": "button" | "reset" | "submit";
        "weight": "slim" | "normal" | "strong";
    }
    interface MyDialog {
        "open": boolean;
    }
    interface MyMenu {
    }
    interface MyMenuItem {
    }
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyDialogElement extends Components.MyDialog, HTMLStencilElement {
    }
    var HTMLMyDialogElement: {
        prototype: HTMLMyDialogElement;
        new (): HTMLMyDialogElement;
    };
    interface HTMLMyMenuElement extends Components.MyMenu, HTMLStencilElement {
    }
    var HTMLMyMenuElement: {
        prototype: HTMLMyMenuElement;
        new (): HTMLMyMenuElement;
    };
    interface HTMLMyMenuItemElement extends Components.MyMenuItem, HTMLStencilElement {
    }
    var HTMLMyMenuItemElement: {
        prototype: HTMLMyMenuItemElement;
        new (): HTMLMyMenuItemElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
        "my-dialog": HTMLMyDialogElement;
        "my-menu": HTMLMyMenuElement;
        "my-menu-item": HTMLMyMenuItemElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        "disabled"?: boolean;
        "type"?: "button" | "reset" | "submit";
        "weight"?: "slim" | "normal" | "strong";
    }
    interface MyDialog {
        "onOpenChanged"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface MyMenu {
    }
    interface MyMenuItem {
    }
    interface IntrinsicElements {
        "my-button": MyButton;
        "my-dialog": MyDialog;
        "my-menu": MyMenu;
        "my-menu-item": MyMenuItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-dialog": LocalJSX.MyDialog & JSXBase.HTMLAttributes<HTMLMyDialogElement>;
            "my-menu": LocalJSX.MyMenu & JSXBase.HTMLAttributes<HTMLMyMenuElement>;
            "my-menu-item": LocalJSX.MyMenuItem & JSXBase.HTMLAttributes<HTMLMyMenuItemElement>;
        }
    }
}
